
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const tableLayout = ({ children }) => {

    return (
        <div>
            {children}
        </div>
    );
};

export default tableLayout;

