import styles from '@/app/(table)/style.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <html >
      <body>
        <div className={styles.homePage}>
          {children}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;

